name: Merge Conflict Notification

on:
  pull_request:
    types:
      - synchronize

jobs:
  send_notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        npm install -g yarn
        yarn install
        
    - name: Check for merge conflicts
      run: |
        git merge --no-commit --no-ff ${{ github.base_ref }}
        if [ $? -eq 0 ]; then
          echo "No merge conflict detected."
          exit 0
        else
          echo "Merge conflict detected."
          git --no-pager diff
          echo "::set-output name=merge_conflict::true"
          exit 1
        fi
    
    - name: Send notification to Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_MESSAGE: |
          :warning: Merge conflict detected in repository: ${{ github.repository }}
          Commit: ${{ github.sha }}
          Branch: ${{ github.ref }}
